### ISSUE TITLE
pip3 install prctl failed

### ISSUE THREAD

**Issue by airkid** [seveas/python-prctl#10]
pip3 install prctl
Downloading/unpacking prctl
  Downloading prctl-1.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_sduacm/prctl/setup.py) egg_info for package prctl
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_sduacm/prctl/setup.py", line 6, in <module>
        import paver.tasks
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 2164, in _find_spec
      File "<frozen importlib._bootstrap>", line 1940, in find_spec
      File "<frozen importlib._bootstrap>", line 1916, in _get_spec
      File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
      File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
      File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location
      File "paver-minilib.zip/paver/tasks.py", line 68
        print output
                   ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_sduacm/prctl/setup.py", line 6, in <module>

    import paver.tasks

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load

  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 2164, in _find_spec

  File "<frozen importlib._bootstrap>", line 1940, in find_spec

  File "<frozen importlib._bootstrap>", line 1916, in _get_spec

  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec

  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader

  File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location

  File "paver-minilib.zip/paver/tasks.py", line 68

    print output

               ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_sduacm/prctl
Storing debug log for failure in /tmp/tmpy15to0et

**Comment by seveas** [comment]
That's a bug in your environment. You are using paver instead of the real pip and it is apparently not compatible with python 3.

**Comment by seveas** [comment]
Actually, I misread that. You're installing the prctl package, which is old and unrelated to this project, which isthe python-prctl package.
